spring:
  profiles:
    active: local
  batch:
    job:
      names: ${job.name:helloJob}

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/stock
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: stockadmin
    password: keepdiscipline
  jpa:
    show-sql: true
    generate-ddl: false
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        show_sql: true
  batch:
    jdbc:
      initialize-schema: ALWAYS